services:
  - type: web
    name: rust-chat-app
    env: rust
    buildCommand: "cargo build --release"
    startCommand: "./target/release/live_chat"
    plan: free
    envVars:
      - key: RUST_LOG
        value: info
